export const MSG = {
  // Side Panel -> Service Worker -> Content Script
  START_FULL_SCAN: 'START_FULL_SCAN',
  START_ELEMENT_SELECT: 'START_ELEMENT_SELECT',
  CANCEL_OPERATION: 'CANCEL_OPERATION',

  // Content Script -> Service Worker -> Side Panel
  SCAN_PROGRESS: 'SCAN_PROGRESS',
  SCAN_COMPLETE: 'SCAN_COMPLETE',
  ELEMENT_SELECTED: 'ELEMENT_SELECTED',
  SCAN_ERROR: 'SCAN_ERROR',

  // Internal
  CONTENT_READY: 'CONTENT_READY',
};
